<?php
// Version de la bdd : 0.0.2.0.0.5(+1) 

define('TBL_CHAT_INTERNE_EQUIPE', 'chat_interne_equipe');

define('CHAT_INTERNE_EQUIPE_ID','ID');
define('CHAT_INTERNE_EQUIPE_CONTENT','CONTENT');
define('CHAT_INTERNE_EQUIPE_ID_USER','ID_USER');
define('CHAT_INTERNE_EQUIPE_ID_EQUIPE','ID_EQUIPE');
define('CHAT_INTERNE_EQUIPE_DATE','DATE');

define('TBL_CHAT_INTER_EQUIPE', 'chat_inter_equipes');

define('CHAT_INTER_EQUIPE_CONTENT','CONTENT');
define('CHAT_INTER_EQUIPE_ID_USER','ID_USER');
define('CHAT_INTER_EQUIPE_ID_EQUIPE_U','ID_EQUIPE_USER');
define('CHAT_INTER_EQUIPE_ID_EQUIPE2','ID_EQUIPE2');
define('CHAT_INTER_EQUIPE_DATE','DATE');

define('TBL_CHAT_USER_TEAM', 'chat_user_team');

define('CHAT_USER_TEAM_ID','ID');
define('CHAT_USER_TEAM_CONTENT','CONTENT');
define('CHAT_USER_TEAM_ID_USER_CIBLE','ID_USER_CIBLE');
define('CHAT_USER_TEAM_ID_USER_MSG','ID_USER_MSG');
define('CHAT_USER_TEAM_ID_EQUIPE','ID_EQUIPE');
define('CHAT_USER_TEAM_DATE','DATE');

define('TBL_COUP_COEURS_EQUIPES', 'coup_coeurs_equipes');

define('COUP_COEURS_EQUIPES_ID_AMOUREUX','ID_AMOUREUX');
define('COUP_COEURS_EQUIPES_ID_BOGOSS','ID_BOGOSS');
define('COUP_COEURS_EQUIPES_DATE','DATE');
define('COUP_COEURS_EQUIPES_ID','ID');

define('TBL_INVITATIONS_EQUIPE_JOUEUR', 'invitations_equipe_joueur');

define('INVITATIONS_EQUIPE_JOUEUR_ID_INVITANT','ID_INVITANT');
define('INVITATIONS_EQUIPE_JOUEUR_ID_INVITE','ID_INVITE');
define('INVITATIONS_EQUIPE_JOUEUR_ID_EQUIPE','ID_EQUIPE');

define('TBL_INVITATIONS_INTER_EQUIPES', 'invitations_inter_equipes');

define('INVITATIONS_INTER_EQUIPES_ID','ID');
define('INVITATIONS_INTER_EQUIPES_ID_INVITANT','ID_INVITANT');
define('INVITATIONS_INTER_EQUIPES_ID_INVITE','ID_INVITE');
define('INVITATIONS_INTER_EQUIPES_DATE_RENCONTRE','DATE_RENCONTRE');
define('INVITATIONS_INTER_EQUIPES_MONTANT','MONTANT');

define('TBL_LIEN_TEAM_USERS', 'lien_team_users');

define('LIEN_TEAM_USERS_ID_TEAM','ID_TEAM');
define('LIEN_TEAM_USERS_ID_USER','ID_USER');

define('TBL_TEAMS', 'teams');

define('TEAMS_ID','ID');
define('TEAMS_PSEUDO','PSEUDO');
define('TEAMS_PHOTO','PHOTO');
define('TEAMS_NB_PLAYED_M','NB_PLAYED_M');
define('TEAMS_NB_VICTORIES','NB_VICTORIES');
define('TEAMS_SCORE','SCORE');
define('TEAMS_SPORT','SPORT');
define('TEAMS_PICTURE_FILE','PICTURE_FILE');
define('TEAMS_LATITUDE',"LATITUDE");
define('TEAMS_LONGITUDE',"LONGITUDE");
define('TEAMS_CITY',"CITY");
define('TEAMS_COUNTRY',"COUNTRY");
define('TEAMS_LAST_CONNEXION',"LAST_CONNEXION");



define('TBL_USERS', 'users');

define('USERS_ID','ID');
define('USERS_PRENOM','PRENOM');
define('USERS_NOM','NOM');
define('USERS_MAIL','MAIL');
define('USERS_PASSWORD','PASSWORD');
define('USERS_PICTURE_FILE','PICTURE_FILE');
define('USERS_PREFS_SPORT','PREFS_SPORT');
define('USERS_TEL','TELEPHONE');
define('USERS_LATITUDE','LATITUDE');
define('USERS_LONGITUDE','LONGITUDE');
define('USERS_DATE_INSCRIPTION','DATE_INSCRIPTION');
define('USERS_COUNTRY','COUNTRY');
define('USERS_CITY','CITY');
define('USERS_CLE','CLE');

define('TBL_USERS_INACTIF', 'users_inactif');

define('USERS_INACTIF_ID','ID');
define('USERS_INACTIF_PRENOM','PRENOM');
define('USERS_INACTIF_NOM','NOM');
define('USERS_INACTIF_MAIL','MAIL');
define('USERS_INACTIF_PASSWORD','PASSWORD');
define('USERS_INACTIF_TEL','TELEPHONE');
define('USERS_INACTIF_LATITUDE','LATITUDE');
define('USERS_INACTIF_LONGITUDE','LONGITUDE');
define('USERS_INACTIF_DATE_INSCRIPTION','DATE_INSCRIPTION');
define('USERS_INACTIF_CLE','CLE');
define('USERS_INACTIF_COUNTRY','COUNTRY');
define('USERS_INACTIF_CITY','CITY');

define('TBL_OFFRE_TEAM_USERS', 'offre_team_users');

define('OFFRE_TEAM_USERS_ID_TEAM','ID_TEAM');
define('OFFRE_TEAM_USERS_DESCRIPTION','DESCRIPTION');
define('OFFRE_TEAM_USERS_NB','NB');
define('OFFRE_TEAM_USERS_FREQUENCE','FREQUENCE');
define('OFFRE_TEAM_USERS_NIVEAU','NIVEAU');

define('TBL_MATCHES', 'matches');

define('MATCHES_ID','ID');
define('MATCHES_DATE','DATE');
define('MATCHES_ID_TEAM1','ID_TEAM1');
define('MATCHES_ID_TEAM2','ID_TEAM2');
define('MATCHES_VICTOIRE','VICTOIRE');
define('MATCHES_RESULTAT','RESULTAT');
define('MATCHES_VALIDE', 'VALIDE');
define('MATCHES_AVIS_SUR1', 'AVIS1');
define('MATCHES_FAIRPLAY_SUR1', 'FAIRPLAY1');
define('MATCHES_AVIS_SUR2', 'AVIS2');
define('MATCHES_FAIRPLAY_SUR2', 'FAIRPLAY2');

define('TBL_SIGNALS_TEAMS', 'signals_teams');

define('SIGNALS_TEAMS_ID_TEAM1','ID_TEAM1');
define('SIGNALS_TEAMS_ID_TEAM2','ID_TEAM2');
define('SIGNALS_TEAMS_DATE','DATE');

define('TBL_REF_SPORTS', 'ref_sports');

define('REF_SPORTS_ID','ID');
define('REF_SPORTS_NOM','NOM');

define('TBL_VIEW_MATCHES_VAINQUEUR', 'view_matches_vainqueur');

//define('VIEW_MATCHES_VAINQUEUR_ID','ID');
//define('VIEW_MATCHES_VAINQUEUR_ID_VAINQUEUR','ID_VAINQUEUR');
//define('VIEW_MATCHES_VAINQUEUR_ID_PERDANT','ID_PERDANT');

define('TBL_VIEW_TEAMS_RANK', 'view_teams_rank');

define('VIEW_TEAMS_RANK_ID','ID');
define('VIEW_TEAMS_RANK_RANG','RANG');

define('TBL_LIEN_PREFS_SPORTS_USER', 'lien_prefs_sports_user');

define('LIEN_PREFS_SPORTS_USER_ID_USER','ID_USER');
define('LIEN_PREFS_SPORTS_USER_ID_SPORT','ID_SPORT');
